/* 手元の台帳から取り込む契約データ
 *
 * 設定タブの「用意してある契約を取り込む」で追加される。
 * id が一致する契約がすでにあれば、取り込みは行わない（二重登録の防止）。
 *
 * 金額は円。分からない項目は amount を null のままにし、limitText に証券の記載を入れている。
 */

const HOKEN_PRESETS = [
  {
    id: "INS-CHUDEN-001",
    ledgerUpdatedAt: "2026-09-21",
    category: "group",
    productType: "group_plan",
    insurer: "三井住友海上火災保険（引受）／全国電力生活協同組合連合会（保険契約者）／中電クラビス（取扱代理店）",
    productName: "ささえ愛 総合医療保障プラン（基本契約 ファミリーセット1口＋携行品損害保障）",
    status: "active",
    startDate: "", endDate: "", isWholeLife: false,
    premium: { amount: 3050, cycle: "monthly", payUntilAge: null },
    paymentMethod: "生協登録口座からの自動引落し（毎月）",
    coveredPersons: "基本契約ファミリーセット：組合員本人・配偶者・同居の親族・別居の未婚の子（賠償責任保障はセットに関わらずファミリーセットの範囲が対象）",
    contractTerms: {
      termType: "1年自動更新（毎年12月1日午後4時に更新）",
      renewalPeriod: "2026年12月1日 午後4時 〜 2027年12月1日 午後4時",
      clauses: [
        "基本契約：普通傷害保険（ケガの保障・日常生活賠償・受託物賠償）",
        "携行品損害保障：団体総合生活補償保険（標準型）／携行品損害補償特約・新価保険特約 ほか",
        "中電生協の組合員であれば退職後も継続加入できる（本人・配偶者・親は100歳まで）",
      ],
    },
    coverages: [
      {
        kind: "accident",
        group: "基本契約 ケガの保障",
        title: "ケガで死亡（傷害死亡保険金）",
        details: "国内外を問わず、事故によるケガのため死亡した場合。病気による死亡は対象外。",
        limitText: "350万円（1口あたり）",
        amount: 3500000, deductible: 0, termYears: null, minGuaranteeYears: null,
        conditions: ["事故の発生の日からその日を含めて180日以内に死亡した場合"],
        exclusions: [], note: "ケガによる死亡のみ。病死では支払われないため、もしもの計算には入れていない。",
      },
      {
        kind: "accident",
        group: "基本契約 ケガの保障",
        title: "ケガで後遺障害（傷害後遺障害保険金）",
        details: "事故によるケガで後遺障害が残った場合。等級に応じた割合で支払われる。",
        limitText: "1〜7級は350万円×所定の割合、8〜14級は175万円×所定の割合（1口あたり）",
        amount: null, deductible: 0, termYears: null, minGuaranteeYears: null,
        conditions: [], exclusions: [], note: "",
      },
      {
        kind: "hospital_daily",
        group: "基本契約 ケガの保障",
        title: "ケガで入院（傷害入院保険金）",
        details: "事故によるケガで入院した場合。1日目から支払われる。",
        limitText: "日額5,000円（1口あたり）",
        amount: 5000, deductible: 0, termYears: null, minGuaranteeYears: null,
        conditions: [], exclusions: [], note: "",
      },
      {
        kind: "outpatient_daily",
        group: "基本契約 ケガの保障",
        title: "ケガで通院（傷害通院保険金）",
        details: "事故によるケガで通院した場合。入院の有無を問わない。",
        limitText: "日額2,000円（1口あたり）",
        amount: 2000, deductible: 0, termYears: null, minGuaranteeYears: null,
        conditions: [], exclusions: [], note: "",
      },
      {
        kind: "surgery",
        group: "基本契約 ケガの保障",
        title: "ケガで手術（傷害手術保険金）",
        details: "事故によるケガで手術を受けた場合。",
        limitText: "傷害入院保険金日額の5倍（入院中以外の手術）／10倍（入院中の手術）",
        amount: null, deductible: 0, termYears: null, minGuaranteeYears: null,
        conditions: [], exclusions: ["傷の処置や抜歯等は対象外"], note: "",
      },
      {
        kind: "liability",
        group: "基本契約 賠償責任保障",
        title: "日常生活賠償",
        details: "他人にケガをさせたり、他人の物を壊して法律上の損害賠償責任を負ったとき。",
        limitText: "1事故につき3億円限度",
        amount: 300000000, deductible: 0, termYears: null, minGuaranteeYears: null,
        settlementService: true,
        conditions: [
          "示談交渉サービスは日本国内で発生した事故のみ",
          "基本契約に2口加入した場合でも保障額はこの限度",
          "夫婦セット・パーソナルセットでもファミリーセットの家族範囲が対象",
        ],
        exclusions: [], note: "",
      },
      {
        kind: "liability",
        group: "基本契約 賠償責任保障",
        title: "受託物賠償責任",
        details: "他人から借りた物（日本国内で借りた物に限る）を壊した場合の賠償。",
        limitText: "保険期間中の支払限度額 30万円限度",
        amount: 300000, deductible: 5000, termYears: null, minGuaranteeYears: null,
        settlementService: false,
        conditions: [], exclusions: [], note: "示談交渉サービスはセットされていない。",
      },
      {
        kind: "property",
        group: "その他オプション",
        title: "携行品損害保障",
        details: "国内外を問わず、住宅（敷地を含む）外で携行している本人所有の身の回り品が、偶然な事故で破損・盗難などの損害を受けたとき。",
        limitText: "保険期間中の支払限度額 20万円限度",
        amount: 200000, deductible: 3000, termYears: null, minGuaranteeYears: null,
        conditions: [
          "1個・1組・1対について損害額が10万円を超えるときは10万円が限度（現金類・乗車券等は5万円が限度）",
          "損害額は修理費または再調達価額のいずれか低い方が限度",
          "盗難は警察への届出が必要",
        ],
        exclusions: [
          "置き忘れ・紛失による損害",
          "自然の消耗・劣化、さび・かび・虫食いなど",
          "すり傷・へこみなど機能の低下を伴わない外観上の損傷のみ",
          "偶然な外来の事故によらない電気的・機械的事故（故障等）",
          "地震・噴火・津波による損害",
        ],
        note: "スマートフォンの破損はパンフレットに支払例として記載あり（会社で落として壊した場合）。",
      },
      {
        kind: "service",
        group: "付帯サービス",
        title: "生活サポートサービス（無料の電話相談）",
        details: "健康・医療相談（24時間）、メンタルヘルス相談、医療機関の情報提供、介護・認知症の相談（24時間）、暮らしの法律相談・税務相談、子育て相談など。加入者本人とその同居の家族が利用できる。",
        limitText: "無料",
        amount: null, deductible: 0, termYears: null, minGuaranteeYears: null,
        conditions: ["暮らしの相談は平日14:00〜17:00、情報提供・紹介は平日10:00〜17:00"],
        exclusions: [], note: "電話相談のサービス。水回りや鍵の駆けつけ修理サービスではない。",
      },
    ],
    beneficiary: "",
    storageNote: "",
    contactNote: "取扱代理店：中電クラビス／引受保険会社：三井住友海上火災保険",
    memo: "月額3,050円は「基本契約ファミリーセット1口 2,800円＋携行品損害保障（ファミリー）250円」と一致するため、この構成として登録している。加入者証で要確認。内容は2026年度パンフレットに基づく。",
    overlapNotes: [
      "日常生活賠償（3億円・示談交渉付）は、日新火災の火災保険の個人賠償責任（1億円・示談交渉付）と重複",
      "ささえ愛には賃貸住宅保障（借家人賠償・修理費用）のオプションもあり、加入していれば火災保険とさらに重複する",
      "携行品損害は住宅外が対象。火災保険の家財（室内）とは重ならない",
      "傷害死亡350万円はケガによる死亡のみで、病気による死亡は対象外",
    ],
  },

  {
    id: "INS-NISSHIN-FIRE-001",
    ledgerUpdatedAt: "2026-09-21",
    category: "nonlife",
    productType: "fire",
    insurer: "日新火災海上保険",
    productName: "賃貸家財総合保険（マイ日新 管理契約）",
    status: "active",
    startDate: "", endDate: "", isWholeLife: false,
    /* 保険料は台帳に記載がないため未登録 */
    premium: { amount: 0, cycle: "annual", payUntilAge: null },
    paymentMethod: "クレジットカード（登録方式）",
    coveredPersons: "",
    contractTerms: {
      termType: "1年自動継続",
      renewalPeriod: "2027-08-02 16:00 〜 2028-08-02 16:00",
      clauses: [
        "初回保険料の払込みに関する特約【6Y】",
        "クレジットカードによる保険料支払に関する特約(登録方式)【2M】",
        "保険契約の自動継続に関する特約【94】",
        "賠償事故の解決に関する特約（示談交渉サービス）",
      ],
    },
    coverages: [
      {
        kind: "property",
        group: "家財補償",
        title: "家財一式（損害防止・残存物取片づけ含む）",
        details: "火災、破裂・爆発、水ぬれ、落雷、物体の飛来・落下、騒擾、風災・雹災・雪災、盗難、通貨・預貯金証書の盗難",
        limitText: "500,000円",
        amount: 500000, deductible: 0, termYears: null, minGuaranteeYears: null,
        conditions: [
          "風災・雹災・雪災は損害額20万円以上で対象",
          "盗難時の通貨は20万円、預貯金証書は200万円または家財保険金額のいずれか低い額が限度",
        ],
        exclusions: [], note: "",
      },
      {
        kind: "expense",
        group: "費用補償",
        title: "借用戸室の修理費用",
        details: "火災、破裂・爆発、水ぬれ、落雷、外部衝突、騒擾、風雹雪災、盗難により賃借住宅を修理した費用",
        limitText: "3,000,000円",
        amount: 3000000, deductible: 0, termYears: null, minGuaranteeYears: null,
        conditions: [], exclusions: [], note: "",
      },
      {
        kind: "liability",
        group: "賠償責任",
        title: "借家人賠償責任",
        details: "火災、破裂・爆発、給排水設備事故等による水ぬれで家主に対して負う法律上の損害賠償",
        limitText: "20,000,000円",
        amount: 20000000, deductible: 0, termYears: null, minGuaranteeYears: null,
        conditions: [], exclusions: [], note: "",
      },
      {
        kind: "liability",
        group: "賠償責任",
        title: "個人賠償責任（示談代行付）",
        details: "日常生活の偶然の事故で他人にケガをさせたり物を壊した賠償責任",
        limitText: "100,000,000円",
        amount: 100000000, deductible: 0, termYears: null, minGuaranteeYears: null,
        settlementService: true,
        conditions: [], exclusions: [], note: "",
      },
      {
        kind: "legal",
        group: "法務支援",
        title: "被害事故法律相談費用等",
        details: "自身が被害者となった事故における弁護士等への相談費用",
        limitText: "300,000円（年間通算）",
        amount: 300000, deductible: 0, termYears: null, minGuaranteeYears: null,
        conditions: [], exclusions: [], note: "",
      },
    ],
    beneficiary: "",
    storageNote: "",
    contactNote: "",
    memo: "",
    overlapNotes: [
      "ささえ愛（基本契約）の日常生活賠償3億円と重複。どちらも示談交渉サービス付き",
      "本火災保険には『示談交渉サービス（賠償事故の解決に関する特約）』が付帯",
      "火災保険の家財は『敷地内（室内）』限定。敷地外の持ち出し品は『ささえあい（携行保証）』がカバー",
    ],
  },
];
